racker/salus-common

src/main/java/com/rackspace/salus/common/web/ReposeHeaderFilter.java
Add a debug log when the Repose header filter has processed an authentication so we can see it when running our apps with "dev" profile enabled.
Manually when running something like public API with "secure" profile enabled
none
=> Add debug log when Repose header filter processes an authentication

src/main/java/com/rackspace/salus/common/messaging/KafkaMessageKey.java, src/main/java/com/rackspace/salus/common/messaging/KafkaMessageKeyBuilder.java, src/test/java/com/rackspace/salus/common/messaging/KafkaMessageKeyBuilderTest.java
Related to the epic SALUS-112
Adds a (proposed) strategy to both declare/document the Kafka message keys for a given event class, but also provides a means to consistently build the key itself.
Adds a custom annotation to declare the properties to include within that event's key. It also adds a utility class to process an instance of those annotated classes into a message key string. I considered declaring it as a Spring component/service, but it doesn't contain any business logic or similar that warrants being a full-blown component.
A unit test has been added.
An alternative could be to simply document the intended keys and perform string concatenations, but the annotation and utility both document and solve the need.
none
=> Add a KafkaMessageKey annotation and builder to process that

src/main/java/com/rackspace/salus/common/messaging/KafkaMessageKeyBuilder.java, src/test/java/com/rackspace/salus/common/messaging/KafkaMessageKeyBuilderTest.java
Inspired by https://github.com/racker/salus-telemetry-resource-management/pull/1 this adds another utility method for composing a key out of arbitrary parts. This is useful when the constituent fields of the kafka message to send are not readily available at the top level of a POJO.
Includes new unit tests
=> Add buildMessageKeyFromParts to KafkaMessageKeyBuilder

src/main/java/com/rackspace/salus/common/messaging/EnableSalusKafkaMessaging.java, src/main/java/com/rackspace/salus/common/messaging/KafkaTopicProperties.java
From discussion in https://github.com/racker/salus-telemetry-resource-management/pull/1 this PR proposes a Spring Boot "Enable" annotation to centralize the activation of kafka topics properties and eventually any other Spring context activations needed across all of our apps that use Kafka.
It provides a single annotation that simplifies and abstracts any cross-app Spring configuration. Applications could have done the `@EnableConfigurationProperties` directly, but it would get tedious.
Existing unit tests and/or manual testing.
I'll also push a PR for https://github.com/racker/salus-telemetry-ambassador that shows how this can be used.
=> Provide common kafka topics configurability

src/main/java/com/rackspace/salus/common/messaging/KafkaTopicProperties.java
Found during SALUS-186
Since Spring Boot is [a little bit inconsistent](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-relaxed-binding) with the environment variable binding, this hierarchical prefix will definitively map to vars like `SALUS_KAKFA_TOPICS_METRICS`.
Tweak the properties prefix, which currently has no impact on anything since the defaults are what we use throughout.
We need to update resource-management and presence-monitor to use these topics properties.
=> Use a better properties prefix for kafka topics properties

src/main/java/com/rackspace/salus/common/messaging/KafkaTopicProperties.java
Part of https://jira.rax.io/browse/SALUS-263
Added a topic property and default for zone events.
=> Add kafka topic for zone events

src/main/java/com/rackspace/salus/common/workpart/services/WorkAllocator.java
While watching a build I noticed the unit tests were outputting a lot of logs like
```
15:34:44.632 [pool-99-thread-6] INFO  c.r.s.c.w.services.WorkAllocator - Result of grab txn = header {
cluster_id: 14841639068965178418
member_id: 10276657743932975437
revision: 11
raft_term: 2
}
succeeded: true
responses {
response_put {
header {
revision: 11
}
}
}
responses {
response_put {
header {
revision: 11
}
}
}
```
Lowered that log message to debug, which is what it was meant to be. It was probably raised for helping with debugging an issue.
Existing unit tests
=> Lower log level of "Result of grab txn" to debug

src/main/java/com/rackspace/salus/common/util/CIDRUtils.java
Adds a utility to validate whether a string is valid CIDR format or not.
Stolen from github! - https://github.com/edazdarevic/CIDRUtils
I added tests for the custom validation that uses this to https://github.com/racker/salus-telemetry-monitor-management/pull/31 - `ValidCidrListValidatorTest`
`org.apache.commons.net.util.SubnetUtils` does not support IPv6 - see issues created in 2011 - https://issues.apache.org/jira/browse/NET-405
I couldn't find any other good alternative.  The other similar libraries would either validate an IP and not a range, or validate an ip is within a range, not that the range given is valid.
=> Add CIDR Util

src/main/java/com/rackspace/salus/common/env/LocalhostPropertySourceProcessor.java, src/main/java/com/rackspace/salus/common/web/AbstractRestExceptionHandler.java, src/main/java/com/rackspace/salus/common/web/ExtendedErrorAttributesConfig.java, src/main/resources/META-INF/spring.factories
Part of https://jira.rax.io/browse/SALUS-413
From Jira issue:
> Since we have at least one "proxy" layer for all of our API handling (such as api-public), it can be confusing when looking at an error response where the error truly originated. The changes from this issue will augment the standard Spring Boot error JSON response with an "app" and "host" field.
Follows the pattern of Spring Boot's random value property source
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-random-values
by auto-configuring a "localhost" property source that simplifies access to the current node's hostname (and IP address). This will consolidate a pattern we've had to repeat in a few places such as …
=> Create localhost property source and extend error attributes config

src/main/java/com/rackspace/salus/common/web/PreAuthenticatedFilter.java, src/main/java/com/rackspace/salus/common/web/ReposeHeaderFilter.java, src/test/java/com/rackspace/salus/common/web/PreAuthenticatedFilterTest.java
Handles x-roles and x-impersonation-roles when using things like the repose header filter.
Repose sends the headers down as a comma separated string in a single header.  It now reads these one value vs. trying to get a list of headers for each one.
I also updated it so it will look at impersonation roles in addition to user roles.
Added a unit test
We'll test after deploying to be certain.
The original logic expected multiple headers to be found for x-roles vs. the one list.  It also didn't look at impersonation roles.  This should allow us to auth correctly to the public/admin apis and also the auth service.
```
Granted Authorities: ROLE_MONITORING_ADMIN,DEDICATED_DEFAULT,TICKETING_ADMIN,IDENTITY_USER_ADMIN
```
This is returning one single authority vs. many.  That is why it looks like …
=> Update role based auth

src/main/java/com/rackspace/salus/common/workpart/config/EtcdConfig.java
This logic does not need to be in `common` as it is already in `etcd-adapter`.  Any service that interacts with `etcd` will now use that service.
This just cleans up our dependencies a little bit.
Relates to https://github.com/racker/salus-telemetry-api/pull/39 and an upcoming presence monitor PR.
=> Remove etcd details

src/main/java/com/rackspace/salus/common/util/ConfigMetadata.java, src/main/java/com/rackspace/salus/common/util/DumpConfigProperties.java
This was my hack day project to give us a way to interrogate a Spring Boot app for all its known configuration properties including the environment variable name for each.
I manually tested this by adding the code shown in the javadoc to the ambassador's main method and invoked it passing `--dump-config=ambassador`, which produced the output:
```
Name | Type | Default | Description | Environment Variable
-----|------|---------|-------------|---------------------
ambassador.alt-external-names | List of String | 127.0.0.1 |  | AMBASSADOR_ALTEXTERNALNAMES
ambassador.cert-chain-path | String | certs/out/ambassador.pem |  | AMBASSADOR_CERTCHAINPATH
ambassador.disable-tls | Boolean | false | FOR DEVELOPMENT ONLY, disable TLS including mutual TLS authentication | AMBASSADOR_DISABLETLS …
```
=> Added utility for dumping Spring Boot config metadata properties

pom.xml
https://jira.rax.io/browse/SALUS-465
Removes tomcat from the library modules so that the apps can select the webserver to use.
Insomnia, run a post with a missing field and see that you see a proper error message instead of:  "Illegal or missing hexadecimal sequence in chunked-encoding".
=> remove tomcat

cloudbuild-deploy.yaml, cloudbuild.yaml, pom.xml
While watching the builds for the Java 11 upgrade I noticed this one still had the old cloudbuild definitions that were missing repo caching and the quieter maven logging.
Copied over one the recent cloudbuild definitions and adjust the project name.
=> Update cloudbuild definitions

src/main/resources/META-INF/additional-spring-configuration-metadata.json
https://jira.rax.io/browse/SALUS-544
Since there's not yet a UMB instance per cluster/environment (dev, staging, prod), then we need to differentiate our kafka consumer group declarations to avoid application instances from multiple clusters all joining the same consumer group.
In this particular library we just pre-declare the property using [this mechanism](https://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html#configuration-metadata-additional-metadata). Each of the applications that will make use of this will need to declare the following default since Spring Boot doesn't seem to be actually using that `defaultValue` across apps:
```yaml
salus:
environment: local
```
Here is an example of how this property in turn will be used to qualify our kafka …
=> Add descriptor of salus.environment

pom.xml, src/main/java/com/rackspace/salus/common/workpart/Bits.java, src/main/java/com/rackspace/salus/common/workpart/config/EtcdConfig.java, src/main/java/com/rackspace/salus/common/workpart/services/WorkAllocator.java, src/test/java/com/rackspace/salus/common/workpart/services/WorkAllocatorTest.java
https://jira.rax.io/browse/SALUS-474
This is one of our two modules that uses the jetcd library. Since they are still 0.x they took some liberties with the API switch from 0.0.2 to 0.3.0. (Already notice the change in semantic version position there.)
- Use the new `io.etcd` group for dependencies. They now maintain the unit testing `jetcd-launcher`.
- Switch package references to `io.etcd.jetcd`
- The API leverages more of the asynchronous features of the etcd protocol, such as with the watcher. No longer need to do our own blocking `listen` call
- The string conversion calls don't make their own character set assumptions
- Some of the "data" types are now "top level" types in `io.etcd.jetcd`
Existing unit tests all pass still
=> Upgraded to jetcd 0.3.0

src/main/java/com/rackspace/salus/common/web/EnableExtendedErrorAttributes.java, src/main/java/com/rackspace/salus/common/web/ExtendedErrorAttributesConfig.java
Seeing this
https://github.com/racker/salus-policy-management/pull/1/files#diff-6c05132d25a2c200983a35bf570c8cb3R28
made me realize that I should have declared an "enable" annotation when adding the config bean. Then it keeps are opt-in feature enabling consistently readable.
Add a class-level annotation that `Import`s the config bean.
=> Add an "enable" annotation for ExtendedErrorAttributes

src/main/java/com/rackspace/salus/common/util/ResourceUtils.java, src/main/java/com/rackspace/salus/common/util/SpringResourceUtils.java
https://jira.rax.io/browse/SALUS-480
This is just creating  a utility function in a common location so that we can read in the SQL templates
We were already using this in testing to load in resource files as String's so I figured why not just use it to load up the SQL files as well.
=> added a utility class to be able to read in java resource files as a String

src/main/java/com/rackspace/salus/common/web/AbstractRestExceptionHandler.java
Needed during https://jira.rax.io/browse/SALUS-592
Following up from this comment https://github.com/racker/salus-telemetry-monitor-management/pull/81#discussion_r319605964 , this change allows for the `message` within the error response body to be replaced with a more specific one.
A delegate method was introduced rather than changing the original since there were 15 uses across 5 repos of the original, two-paramter one.
=> Provide an option to override message in AbstractRestExceptionHandler

src/main/java/com/rackspace/salus/common/web/AbstractRestExceptionHandler.java, src/main/java/com/rackspace/salus/common/web/RemoteOperations.java, src/main/java/com/rackspace/salus/common/web/RemoteServiceCallException.java, src/test/java/com/rackspace/salus/common/web/RemoteOperationsTest.java
Part of https://jira.rax.io/browse/SALUS-634
When monitor management is missing one of the `salus.services` properties, the `RestTemplate` call throws an `IllegalArgumentException` with very little information. In turn, the response to the original monitor management call, such as when creating a monitor, has a status code of 400 and a body of
```json
{
"timestamp": "2019-09-30T18:30:43.792+0000",
"status": 400,
"error": "Bad Request",
"message": "URI is not absolute",
"app": "salus-telemetry-monitor-management",
"host": "monitor-management-5f7db89967-cj54d"
}
```
The logs contain no indication of what originally induced the "URI is not absolute" -- I was only able to narrow this one down to a `RestTemplate` call because I know we do the `RestTemplateBuilder` stuff in our client …
=> Provide better handling of exceptions thrown by RestTemplate

src/main/resources/logback-fluency.xml
Related to https://jira.rax.io/browse/SALUS-653
I discovered that inclusions from within `logback-spring.xml` can access a config file situated in `salus-common`, so now we can make app wide changes in one spot and avoid a duplicated file.
...I also enhanced the fluentd tag to include the `spring.application.name` property so that fluentd configs can match on that tag more precisely and we can convey the app name into the final ES stored log documents, such as
```json
{
"level": "INFO",
"logger": "org.springframework.security.web.DefaultSecurityFilterChain",
"thread": "main",
"message": "Creating filter chain: any request, ...",
"@timestamp": "2019-10-23T21:21:25.000000000+00:00",
"tag": "application.salus-api-public"
}
```
Manually
Remove `logback-fluency.xml` from our applications after …
=> Declared shared fluency config that uses application name in tag

pom.xml, src/main/java/com/rackspace/salus/common/messaging/EnableSalusKafkaMessaging.java, src/main/java/com/rackspace/salus/common/messaging/KafkaErrorConfig.java
https://jira.rax.io/browse/SALUS-668
Exceptions thrown within kafka deserializers are processed within the lower layers of Spring Kafka, so the `@KafkaListener` method never gets called and the consumer never moves beyond any malformed messages in the metrics topic.
By stitching together some documentation, poking around in Spring Boot code, and an SO answer I found how to register an error handler that can skip bad messages and optionally log the content and cause of the bad message:
- https://docs.spring.io/spring-kafka/reference/html/#error-handling-deserializer
- https://docs.spring.io/spring-kafka/reference/html/#container-error-handlers
- https://github.com/spring-projects/spring-boot/blob/2.1.x/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/auto …
=> Provide common registration for Kafka deserialization error handling

src/main/resources/logback-fluency.xml
https://jira.rax.io/browse/SALUS-715
I noticed our logs in kibana were missing an identification of the pod, which is available via its hostname.
Leverage the properties created by `LocalhostPropertySourceProcessor` to pick off and include the local hostname as a field of the logback payload.
Used the fluentd service in our infra docker compose definitions.
=> Add local hostname as a fluentd field for pod identification

src/main/java/com/rackspace/salus/common/web/RequestLogging.java
https://jira.rax.io/browse/SALUS-725
We didn't have any existing log entries that included the request info, the response status, and the sleuth trace ID all together. As a result, it would have been hard to troubleshoot a specific request reported by one of our users and then pick out the logs associated with that trace.
Based on [this article](https://www.baeldung.com/spring-http-logging), implemented a web mvc interceptor that will get registered by api-public and api-admin. It produces logs that look like:
```
2019-12-13 15:33:28.748  INFO [salus-api-public,da9caf57b709d1f7,da9caf57b709d1f7,true] 28541 --- [qtp284427775-36] c.r.salus.common.web.RequestLogging      : Request completed: method=GET path=/v1.0/tenant/aaaaaa/monitors parameters={} status=502
2019-12-13 15:34:46.722  INFO …
```
=> Provide a web mvc interceptor that logs requests with the response status

src/main/java/com/rackspace/salus/common/messaging/KafkaTopicProperties.java
https://jira.rax.io/browse/SALUS-666
Related to https://github.com/racker/salus-telemetry-presence-monitor/pull/46 this removes the events topic property that was only used by presence monitor.
Remove the topic property.
=> Removed the events topics, which was only used by presence monitor

src/main/java/com/rackspace/salus/common/web/AbstractRestExceptionHandler.java
The Spring Cloud Sleuth traceId gets included in the response header `X-Trace-Id`; however, that doesn't help when only the body of a failed REST response is logged. Likewise, I am guessing users may only provide the response body and not the headers when reporting an API issue to us.
Leverage the request header that Sleuth/Brave adds to requests headers going through api admin/public and include that, when available, as a field in the error response body. Here is an example of one after this change:
```json
{
"timestamp": "2020-01-16T20:27:17.254+0000",
"status": 400,
"error": "Bad Request",
"message": "could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement",
"app": …
```
=> Added Sleuth traceId, when available, to error response entity

pom.xml
Part of https://jira.rax.io/browse/SALUS-738
Bumped Spring Boot version to 2.2.4. No other changes (like the h2->mysql DB stuff) were needed in this module.
=> Bumped Spring Boot version to 2.2.4

src/main/resources/logback-spring.xml
Part of https://jira.rax.io/browse/SALUS-770
- When devops encounters fluentd configuration issues, the logging silently disappears when "production" profile is activated
- I had originally thought the file `logback-spring.xml` couldn't be picked by applications via a library jar in the classpath...I tested the theory and confirmed they actually can
Provide a single, shared copy of `logback-spring.xml` that will allow (in follow PRs) application to no longer need to copy-paste the same file.
This specific change https://github.com/racker/salus-common/commit/7f786c148ee5d52ca20aa862860620c107817a60 shifts the CONSOLE appender out of a profile-conditional and registers it regardless of activate profile(s).
I have verified locally by removing `logback-spring.xml` from an application and …
=> Provided shared logback console config with console appender always registered

pom.xml, src/main/java/com/rackspace/salus/common/config/AutoConfigureSalusAppMetrics.java, src/main/java/com/rackspace/salus/common/config/MetricsConfig.java, src/test/java/com/rackspace/salus/common/config/MetricsConfigTest.java
https://jira.rax.io/browse/SALUS-801 and wanted this during https://jira.rax.io/browse/SALUS-806
We have very similar, but sometimes slightly different, implementations of `MetricsConfig` across some of our apps. It would be good to unify those and avoid re-implementing.
Introduced an annotation `@AutoConfigureSalusAppMetrics` that activates the common `MetricsConfig`. FYI it's an "auto-configure" annotation and not "enable" since the metrics registry is enabled by other means and this is simply auto-configuring that.
Added a unit test
=> Added a common MetricsConfig and auto-config annotation

src/main/java/com/rackspace/salus/common/util/ApiUtils.java, src/main/java/com/rackspace/salus/common/web/ReposeHeaderFilter.java, src/main/java/com/rackspace/salus/common/web/RoleBasedJsonViewControllerAdvice.java
Making sure we use the same header to get the tenant id for everything.
Currently tokens with the `monitoring:service-admin` role are not being allowed through the system.
Due to - https://github.com/Rackspace-Segment-Support/salus-repose-container/pull/13
That change leads to `x-tenant-id` not being set if the tenant validation is skipped.
We populate `requested-tenant-id` from the url requested - https://github.com/Rackspace-Segment-Support/salus-repose-container/blob/master/etc/repose/url-extractor-to-header.cfg.xml
----
The alternative method would be to update the `url-extractor-to-header` filter to instead insert the tenant value as `x-tenant-id`.  If the tenant validation was also ran it would simply overwrite what was already set.  I decided against that to hopefully keep things …
=>  Use consistent tenant header 

src/main/java/com/rackspace/salus/common/util/ApiUtils.java
This is potentially preventing impersonation roles from being passed down to all services.
I say "potentially" because Repose is supposed to merge `X-Impersonator-Roles` into `X-Roles` making this redundant.  Still looking into that part.
=> Fix typo in header name

src/main/java/com/rackspace/salus/common/util/ApiUtils.java, src/main/java/com/rackspace/salus/common/web/ReposeHeaderFilter.java, src/main/java/com/rackspace/salus/common/web/RoleBasedJsonViewControllerAdvice.java
Reverts racker/salus-common#52
We changed our mind.  We're gonna use `x-tenant-id` everywhere.
=> Revert " Use consistent tenant header "

src/main/java/com/rackspace/salus/common/errors/BooleanFormatException.java, src/main/java/com/rackspace/salus/common/util/BooleanParser.java, src/test/java/com/rackspace/salus/common/util/BooleanParserTest.java
https://jira.rax.io/browse/SALUS-783
Adds a new boolean parser for us to use.
This is being added for https://github.com/racker/salus-policy-management/pull/27
=> boolean parser

src/main/java/com/rackspace/salus/common/util/ApiUtils.java, src/main/java/com/rackspace/salus/common/web/PreAuthenticatedFilter.java, src/main/java/com/rackspace/salus/common/web/ReposeHeaderFilter.java
For tokens with multiple tenants available, Repose will pass down all of them in the `X-Tenant-Id` field.  We only care about the one that the request is specifically for, so we will instead use the tenant that Repose parses out of the URL.
This change will be documented in the `keystone-v2-authorization` filter config.
=> Use tenant populated from url parsing

pom.xml
This dependency hasn't been used for a while.  We just need to remove it from the pom.
=> Remove salus-model dependency

pom.xml, src/main/java/com/rackspace/salus/common/config/RoleProperties.java, src/main/java/com/rackspace/salus/common/web/BackendServicesWebSecurityConfig.java, src/main/java/com/rackspace/salus/common/web/PreAuthenticatedFilter.java, src/main/java/com/rackspace/salus/common/web/ReposeHeaderFilter.java, src/test/java/com/rackspace/salus/common/web/PreAuthenticatedFilterTest.java
Some apps were failing to build on 3.7 so I'm bumping the plugin to 3.8 for everything.
The error was something along the lines of `source option 5 is no longer supported` and my search led me to find 3.8 solved this.
This deals with role validation and should not care about tenant validation, so we do not require a tenant to be provided.  This service also spans the public and admin api which is another reason for not requiring a tenant (since the admin api does not provide one).
Updates the Repose Filter so we can tell it whether or not to verify a tenant id was included in the `Requested-Tenant-Id` header.  This is only required for public api requests, so this change allows us to set the option to true for those and false for admin api requests.
It will also now log more useful …
=> Update authentication filters

src/main/java/com/rackspace/salus/common/messaging/KafkaErrorConfig.java
Found during https://jira.rax.io/browse/SALUS-927
I'm not sure why this worked before, but the unit test `com.rackspace.salus.event.ingest.services.IngestServiceKafkaTest#testDeserializerFailure` was now hitting an NPE at the changed lines since the value of the given kafka message was null in the case of a deserialization exception.
Wrap access to the `data.value()` with a null check. The debug logging further down in the method will ultimately convey the payload that failed to deserialize.
Use `com.rackspace.salus.event.ingest.services.IngestServiceKafkaTest#testDeserializerFailure` in event-engine-ingest.
=> Fixed null value handling in KafkaErrorConfig

src/main/java/com/rackspace/salus/common/web/AbstractRestExceptionHandler.java
https://jira.rax.io/browse/SALUS-994
Changed response message for JsonMappingException
Changed AbstractRestExceptionHandler class for JsomMappingException
This can be tested via insomnia REST call
Message displayed for error was not appropriate before
=> Changed response message for JsonMappingException

src/main/java/com/rackspace/salus/common/web/AbstractRestExceptionHandler.java
https://jira.rax.io/browse/SALUS-730
Handling of MethodArgumentNotValidException for inconsistent error messages.
This can be tested via REST call
**Before**
`{
"timestamp": "2020-09-23T11:01:50.037+00:00",
"status": 400,
"error": "Bad Request",
"exception": "org.springframework.web.bind.MethodArgumentNotValidException",
"message": "",
"path": "/api/admin/zones",
"app": "salus-telemetry-monitor-management",
"host": "MCP2AKMD6M"
}`
**After**
`{
"timestamp": "2020-09-23T11:00:05.364+00:00",
"status": 400,
"error": "Bad Request",
"exception": "org.springframework.web.bind.MethodArgumentNotValidException",
"message": "Validation failed for argument [0] in public com.rackspace.salus.monitor_management.web.model.ZoneDTO com.rackspace.salus.monitor_management.web.controller.ZoneApiController.crea …
=> Added exception handler for MethodArgumentNotValidException

src/main/java/com/rackspace/salus/common/web/AbstractRestExceptionHandler.java
https://jira.rax.io/browse/SALUS-827
Handle case for HttpMessageNotReadableException in IllegalStateException handler
This can be tested via REST call
**Before**
**After**
=> Handled case for JsonParseException in IllegalStateException handler

src/main/java/com/rackspace/salus/common/messaging/KafkaTopicProperties.java
https://jira.rax.io/browse/SALUS-1036
A new topic where state change events can be sent.
These are generated by the event-engine-processor based on the state expressions within a task.
=> Add event topics

src/main/java/com/rackspace/salus/common/config/MetricNames.java, src/main/java/com/rackspace/salus/common/config/MetricTags.java
Some new names that I'm using in https://github.com/racker/salus-event-engine-processor/pull/1
I considered "ignored_errors" instead of "silent" but in the end we dont want to ignore them which is why they're tracked here... they just don't cause any exceptions to be thrown.
=> Add more standard metric names/tags

src/main/java/com/rackspace/salus/common/messaging/KafkaErrorConfig.java
During some local testing, @rohitsngh27 ran into a case where a lower level issue with kafka consumer cascaded to a NPE in our `listenerContainerErrorHandler`.
While I was in there, I also noticed that `ErrorHandlingDeserializer2` has been deprecated and renamed to `ErrorHandlingDeserializer` in https://github.com/spring-projects/spring-kafka/pull/1411
Null check the provided `ConsumerRecord data` parameter and log an abbreviated message in that case.
Reference `ErrorHandlingDeserializer` instead of `ErrorHandlingDeserializer2`
Indirectly via kafka consuming applications.
=> Tweaked listenerContainerErrorHandler to check for null ConsumerRecord

src/main/java/com/rackspace/salus/common/messaging/KafkaTopicProperties.java
Used with https://github.com/racker/salus-event-engine-management/pull/75
To be able to generate a partitionid for a task we need to know the total number of partitions on the metrics topic.
=> Add value to track partition count
